# 通用配置
[common]
ip_port = 443
no_save = false
cidr_sample_ip_num = 16

[valid test]
enabled = true
ip_limit_count = 100000
host_name = cloudflare.com
user_agent = false
path = /cdn-cgi/trace
file_check = true
file_url = https://speed.cloudflare.com/__down?bytes=500000000
thread_num = 64
max_retry = 2
retry_factor = 0.5
timeout = 1.5
print_err = false

[rtt test]
enabled = true
ip_limit_count = 100000
interval = 0.5
thread_num = 32
timeout = 0.5
max_rtt = 300
test_count = 10
max_loss = 100
fast_check = false
print_err = false

[speed test]
enabled = true
ip_limit_count = 100000
url = https://speed.cloudflare.com/__down?bytes=500000000
user_agent = false
max_retry = 10
retry_factor = 0.5
timeout = 5
download_time = 10
download_speed = 5000
avg_download_speed = 0
fast_check = false
bt_ip_limit = 0
rm_err_ip = false
print_err = false
